### ISSUE TITLE
Clarity on center prop

### ISSUE THREAD

**Issue by austinbutler** [pradel/react-responsive-modal#184] opened 2018-08-09 21:44 UTC
This problem has been noted at least once (https://github.com/pradel/react-responsive-modal/issues/163), if not twice (https://github.com/pradel/react-responsive-modal/issues/47). I am inferring from the question asked in that first issue and from the `README` (`center` is for "when you don't have a lot of content"), that `center` does not work properly when the height of the modal exceeds the view height, and this is either a known limitation or by design.

It would be helpful to know if there are plans to "fix" this, and if not I think an update to the `README` that's more explicit about the potential drawbacks to `center` as a prop would be helpful.

**Comment by pradel** [comment] 2018-08-10 07:34
Hey, you are totally right, maybe the README is a little bit confusing.
So the current behavior is by design, flex does not allow this option unfortunately.
I will have to update the README to make that more clear 👍

**Comment by omasback** [comment] 2018-08-21 02:54
I found a possible fix for this! https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container
```
.modal {
    margin: auto;
}
```

**Comment by pradel** [comment] 2018-08-28 09:18
Thanks @omasback this looks like a good way to fix this limitation!
I need to try in other browsers but it is working for chrome 🚀

**Closed** 2018-08-28 09:48 UTC

**Comment by pradel** [comment] 2018-08-28 09:55
published as v3.3.0
