### ISSUE TITLE
"Back" button to close the modal.

### ISSUE THREAD

**Issue by aneeshtigga** [pradel/react-responsive-modal#194] opened 2018-08-25 09:05 UTC
Is there a way to set the "Back" button to close an open modal. It'll be handy for long scrollable modals, instead of scrolling back to top in order to close it. "Esc" button is handy for desktop users but not for mobile users.

Any help would be appreciated. and Thanks for this amazing modal by the way.

**Comment by pradel** [comment] 2018-08-27 15:43
In order to achieve that you can modify the css of the button and use `position: fixed` on it :)

**Comment by pradel** [comment] 2018-08-28 09:01
Oh okay so you mean the android back button.
I never faced this use case but maybe take a look at this link https://stackoverflow.com/questions/25806608/how-to-detect-browser-back-button-event-cross-browser.
Otherwise if you are using react-router you can subscribe to route changes in order to update your state.

**Comment by pradel** [comment] 2018-09-17 14:39
Since this issue is not a bug of this package I will close the issue :)

**Closed by pradel** 2018-09-17 14:39 UTC
